# Discord: https://discord.gg/4bAceda9q3
# Github : https://github.com/ValresMC
# By Valres
#
#
# true for all worlds :
all-worlds: "false"
limit: 100

worlds:
  world_1: 100
  world_pvp: 125

# Message :
message: "You have reached the height limit of the world !"